language: python


sudo: required


group: travis_latest

python:
  - "3.7"

cache: pip

jobs: 
  include: 
    - name: Linux Build
      os: linux
      dist: xenial

    - name: MacOS Build
      os: osx
      osx_image: xcode10.2

install:
  - virtualenv --python=python3.7 pmtenv
  - source pmtenv/bin/activate
  - pip install .
  - pushd prometeo/cpmt
  - make install_shared
  - popd
  - export LD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/blasfeo/lib:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/prometeo/lib:$LD_LIBRARY_PATH

script: 
  - pushd examples/simple_example
  - pmt simple_example.py --cgen=True
  - popd

  - pushd examples/test
  - pmt test.py --cgen=True
  - popd

  - pushd examples/riccati
  - pmt riccati.py --cgen=True
  - popd
