
language: python

os: linux

sudo: required

dist: xenial

group: travis_latest

python:
  - "3.7"

cache: pip

install:
  - virtualenv --python=python3.7 pmtenv
  - source pmtenv/bin/activate
  - pip install .
  - pushd prometeo/cpmt
  - make install_shared
  - popd


script: 
  - pmt examples/simple_example/simple_example.py --cgen=True
