
language: c

os: linux

dist: xenial

group: travis_latest

python:
  - "3.7"

cache: pip

install:
  - virtualenv --python=python3.7 pmtenv
  - source pmtenv/bin/activate
  - pip install .

script: 
  - pmt examples/simple_example/simple_example.py --cgen=True
