
language: python

os: linux

sudo: required

dist: xenial

group: travis_latest

python:
  - "3.7"

cache: pip

before_install:
    - choco install python --version 3.7.0

install:
  # - sudo apt-get install python3.7
  - virtualenv --python=python3.7 pmtenv
  - source pmtenv/bin/activate
  - pip install .

script: 
  - pmt examples/simple_example/simple_example.py --cgen=True
