
language: python

os: linux

sudo: required

dist: xenial

group: travis_latest

python:
  - "3.7"

cache: pip

install:
  - virtualenv --python=python3.7 pmtenv
  - source pmtenv/bin/activate
  - pip install .
  - pushd prometeo/cpmt
  - make install_shared
  - popd
  - export LD_LIBRARY_PATH=~/prometeo/prometeo/cpmt/install/blasfeo/lib:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=~/prometeo/prometeo/cpmt/install/proemeteo/lib:$LD_LIBRARY_PATH

script: 
  - pmt examples/simple_example/simple_example.py --cgen=True
