language: python

sudo: required

group: travis_latest

python: 3.7

cache: pip

jobs: 
  include: 
    - name: Linux Build + examples
      os: linux
      dist: xenial

    - name: macOS Build + examples
      os: osx
      osx_image: xcode10.2
      language: shell

install:
  - pip install virtualenv
  - virtualenv --python=python3.7 pmtenv
  - source pmtenv/bin/activate
  - pip install .
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      pushd prometeo/cpmt;
      make install_shared CC=clang TARGET=GENERIC OPT_LD_FLAGS=-Wl,-undefined,dynamic_lookup; 
      popd;
      export DYLD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/blasfeo/lib:$DYLD_LIBRARY_PATH;
      export DYLD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/prometeo/lib:$DYLD_LIBRARY_PATH;
      export LD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/blasfeo/lib:$LD_LIBRARY_PATH;
      export LD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/prometeo/lib:$LD_LIBRARY_PATH;
    else
      pushd prometeo/cpmt;
      make install_shared; 
      popd;
      export LD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/blasfeo/lib:$LD_LIBRARY_PATH;
      export LD_LIBRARY_PATH=$(pwd)/prometeo/cpmt/install/prometeo/lib:$LD_LIBRARY_PATH;
    fi

script: 
  - pushd examples/simple_example
  - pmt simple_example.py --cgen=True
  - pmt simple_example.py --cgen=False
  - popd

  - pushd examples/test
  - pmt test.py --cgen=True
  - pmt test.py --cgen=False
  - popd

  - pushd examples/riccati_example
  - pmt riccati.py --cgen=True
  - pmt riccati.py --cgen=False
  - popd
